In [4]:
import numpy as np


In [6]:
lista = [1,2,3,4]
lista2 = np.array([[1,2,3],[4,5,6]])
print(lista2)

[[1 2 3]
 [4 5 6]]


In [13]:
np.empty([4,4],dtype=int)

array([[    0,     0,     0,     0],
       [    0,     0,     0,     0],
       [    0,     0,  1364,     0],
       [    0,    93,     0, 32767]])

In [14]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [56]:
np.full([4,4],2.3)

array([[2.3, 2.3, 2.3, 2.3],
       [2.3, 2.3, 2.3, 2.3],
       [2.3, 2.3, 2.3, 2.3],
       [2.3, 2.3, 2.3, 2.3]])

In [57]:
np.random.random([4,4])

array([[0.47565611, 0.68772542, 0.14376177, 0.72439286],
       [0.9235087 , 0.25789288, 0.23774097, 0.21237328],
       [0.91436205, 0.14316857, 0.4262889 , 0.90641392],
       [0.82788722, 0.23421667, 0.37631969, 0.08734577]])

In [19]:
np.random.randint(1,50,5)

array([41, 27, 11, 27, 38])

In [58]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.arange(5,20,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [59]:
np.linspace(10,80,6)

array([10., 24., 38., 52., 66., 80.])

In [32]:
ejmA = np.array([[1,2,3,4,5,6],[7,8,9,10,11,43]])
ejmB = np.reshape(ejmA,(4,3))
print(ejmB)
print(ejmA.shape)
print(ejmB.shape)

ejmA.max() 
ejmA.argmax() 
ejmA.min() 
ejmA.argmin() 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 43]]
(2, 6)
(4, 3)


43

In [34]:
a = np.arange(10,50)

a[::-1]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [35]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
r = np.random.random((3,3,3))
print(r)

[[[0.70681684 0.35232309 0.9940939 ]
  [0.18563125 0.11371766 0.44131475]
  [0.84548183 0.50691213 0.29432107]]

 [[0.03735951 0.60794995 0.56322999]
  [0.70243165 0.42923794 0.76750475]
  [0.07783216 0.51104493 0.43240292]]

 [[0.62048318 0.18340952 0.29287271]
  [0.66105071 0.97215871 0.54869227]
  [0.88337939 0.76822933 0.79295572]]]


In [50]:
z = np.ones((10,10))
z[1:-1,1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [54]:
np.tile(np.arange(0,5),5).reshape(5,5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [53]:
a = np.random.random((3,3))
b = np.random.random((3,3))
print(a)
print(b)
a == b

[[0.10561669 0.9896002  0.56290168]
 [0.74329338 0.43598615 0.72709786]
 [0.55019915 0.01047818 0.65475435]]
[[0.95525825 0.17956091 0.07107024]
 [0.87573173 0.30440399 0.09164729]
 [0.43114483 0.47640536 0.16739333]]


array([[False, False, False],
       [False, False, False],
       [False, False, False]])